#!/bin/bash
MY_PATH=$(dirname "$0")
MY_PATH=$(cd "$MY_PATH" && pwd)

# lets check if config exists
if [ ! -f $MY_PATH/config.yaml ]; then
  echo "Configuration not found! Please create config.yaml from config.yaml.template and try again."
  exit 1
fi

# lets load yaml parser function (fn: parse_yaml)
source $MY_PATH/scripts/parse_yaml
eval $(parse_yaml $MY_PATH/config.yaml)

function aqi() {
  if ! screen -list | grep -q "aqi"; then
    echo "starting AQI sensor... screen: aqi"
    screen -S aqi -d -m $MY_PATH/sensors/aqi.py
  else
    screen -S aqi -X quit
    sleep 0.5
    echo "restarting AQI sensor... screen: aqi"
    screen -S aqi -d -m $MY_PATH/sensors/aqi.py
  fi
}

function temp() {
  if ! screen -list | grep -q "temp"; then
    echo "starting Temp sensor... screen: temp"
    screen -S temp -d -m $MY_PATH/sensors/temp.py
  else
    screen -S temp -X quit
    sleep 0.5
    echo "restarting Temp sensor... screen: temp"
    screen -S temp -d -m $MY_PATH/sensors/temp.py
  fi
}

function camera() {
  if ! screen -list | grep -q "camera"; then
    echo "starting camera live stream... screen: camera"
    screen -S camera -d -m $MY_PATH/sensors/camera.sh
  else
    screen -S camera -X quit
    sleep 0.5
    echo "restarting camera live stream... screen: camera"
    screen -S camera -d -m $MY_PATH/sensors/camera.sh
  fi
}

function checkAllServices() {
  for var in "$@"; do
    if ([ $var = "aqi" ] && [ $sensors_measureAqi = true ]); then
      aqi
    fi

    if ([ $var = "temp" ] && [ $sensors_measureTemperature = true ]); then
      temp
    fi

    if ([ $var = "camera" ] && [ $sensors_useCamera = true ]); then
      camera
    fi
  done
}

function restartAllServices() {
    if ([ $sensors_measureAqi = true ]); then
      aqi
    fi

    if ([ $sensors_measureTemperature = true ]); then
      temp
    fi

    if ([ $sensors_useCamera = true ]); then
      camera
    fi
}

if [ $# -eq 0 ]; then
  restartAllServices
else
  checkAllServices $@
fi
